Several Bugfixes: - ProjectModel.findIndex/Item correct AttributeError: 'NoneType' object has no attribute 'index' - Fixing selection of scene items and project panel items - correct icon update of devices belonging to deviceGroup
- karabo_package.project parse function sets project of deviceGroup earlier