"Duplicate" of scene model - still not working correctly due to the following error message
```
  File "/home/wegerk/Development/git/karaboFramework/src/pythonGui/karabo_gui/projectmodel.py", line 1236, in addScene
    sceneModel = read_scene(filename_or_fileobj)
  File "/home/wegerk/Development/git/karaboFramework/src/pythonGui/karabo_gui/scenemodel/io.py", line 15, in read_scene
    tree = parse(filename_or_fileobj)
  File "/home/wegerk/Development/git/karaboFramework/karabo/extern/lib/python3.4/xml/etree/ElementTree.py", line 1187, in parse
    tree.parse(source, parser)
  File "/home/wegerk/Development/git/karaboFramework/karabo/extern/lib/python3.4/xml/etree/ElementTree.py", line 598, in parse
    self._root = parser._parse_whole(source)
  File "<string>", line None
xml.etree.ElementTree.ParseError: no element found: line 1, column 0
```